// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/xozrc/cqrs/eventsourcing (interfaces: EventStore)

package mock_eventsourcing

import (
	gomock "github.com/golang/mock/gomock"
	eventsourcing "github.com/xozrc/cqrs/eventsourcing"
)

// Mock of EventStore interface
type MockEventStore struct {
	ctrl     *gomock.Controller
	recorder *_MockEventStoreRecorder
}

// Recorder for MockEventStore (not exported)
type _MockEventStoreRecorder struct {
	mock *MockEventStore
}

func NewMockEventStore(ctrl *gomock.Controller) *MockEventStore {
	mock := &MockEventStore{ctrl: ctrl}
	mock.recorder = &_MockEventStoreRecorder{mock}
	return mock
}

func (_m *MockEventStore) EXPECT() *_MockEventStoreRecorder {
	return _m.recorder
}

func (_m *MockEventStore) Load(_param0 string, _param1 int64) ([]*eventsourcing.EventEntity, error) {
	ret := _m.ctrl.Call(_m, "Load", _param0, _param1)
	ret0, _ := ret[0].([]*eventsourcing.EventEntity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockEventStoreRecorder) Load(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Load", arg0, arg1)
}

func (_m *MockEventStore) Save(_param0 string, _param1 []*eventsourcing.EventEntity) error {
	ret := _m.ctrl.Call(_m, "Save", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockEventStoreRecorder) Save(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Save", arg0, arg1)
}
